main.go, target.go
First, great job for this exporter ! This is exactly what we need for our network connectivity monitoring.
During exporter set up, we encountered a problem  specific to our network configuration : the last DNS server specified in our resolv.conf resolves public IP instead of private IP for fallback purpose.
It appears Go's default resolver seems to take any DNS server in resolv.conf: that resulted on some IP's flapping issues.
As we just want to check private network connectivity, I added this option to define DNS server used for resolve targets hostnames.
=> Add option to specify dns server used to resolve hostname of targets

main.go
As our log system is flooded by the refresh DNS message, I added this option to define log level used by logger.
A better solution is surely to handle command line with [Kingpin](https://github.com/alecthomas/kingpin) flag parser but this involves
more changes to the codebase.
=> Add option to specify log level

.gitignore, .goreleaser.yml, .travis.yml, go.mod
I've used goreleaser a lot to automatically create binaries/RPMs. I'm submitting this in case you think it's useful. If not, I'm happy to maintain a fork.
This also includes the changes in #12 so that needs to be merged first.
You can build binaries against tags using:
```
goreleaser --rm-dir --skip-publish
```
If you want to have tags built automatically, I can send another PR with travis config. Examples are here: https://github.com/jaxxstorm/ping_exporter/commits/travis
You'll just need to update your travis config with this repos github token.
Let me know what you think.
=> Goreleaser config

.gitignore, config/config.go, config/config_test.go, config/testdata/config_test.yml, main.go
Introduce additional `--payload-size` parameter, which allows customizing the ICMP payload size.
The default value is `56` (which, together with headers, results in `64 bytes`). It matches the default value of [`go-ping`](https://github.com/digineo/go-ping/blob/master/pinger.go#L67), so it does not affect the existing users.
=> Support configurable ICMP payload size

main.go
Currently on our system where ipv6 is disabled the exporter fails to start with:
```
msg="listen ip6:ipv6-icmp ::: socket: address family not supported by protocol" source="main.go:97"
```
I've taken the code to detect ipv4/6 availability from here: https://github.com/golang/net/blob/ca1201d0de80cfde86cb01aea620983605dfe99b/nettest/nettest.go#L37-L44
=> Gracefully handle systems that have ipv4/ipv6 disabled

.gitignore, snap/snapcraft.yaml
This merge adds support for building this package as a snapcraft package.
This allows easy build and distribution on multiple Linux distributions. Automatic build and publishing can be configured on the snapcraft store also, by registering this project and then registering this repository with the package on the store, allowing tagged builds to be released as snap packages folks can install via `snap install` on their machines.
I have configured the daemon used by the snap to look in $SNAP_COMMON for the config.yaml file - this is standard practice, as snapd (the snapcraft runtime) pointed $SNAP_COMMON at a folder accessible both inside and outside the snap, typically under /var/snap/<snapname>/common - which is retained between upgrades (refreshes) of the snap.
=> Added snapcraft packaging

main.go
There's a small logic error when loading the config file: The flags are only applied when the loading failed.
=> Fix defaults when using config file

README.md, collector.go, main.go, rttscale.go
To quote #16:
> To follow the [official Prometheus guidelines](https://prometheus.io/docs/practices/naming/#base-units), as well as [comments from Prometheus developers](https://www.robustperception.io/who-wants-seconds), we should be using seconds as the unit for all ping_rtt metrics (e.g. `ping_rtt_best_seconds` instead of `ping_rtt_best_ms`).
This adds a flag `--metrics.rttunit=s`, to allow the user to follow those best practices.
To keep upgrading users from tripping over this change, the default units will remain millis.
Fixes: #16
=> metrics: allow for best practices

collector.go
Fixing duplicate unit in metric name mentioned in #48
=> remove duplicate unit from metric definition

Dockerfile, README.md
See also the README regarding use.
Other than the bloat of adding `libcap` to the container being run (rather than to the builder -- I just wasn't aware what `golang:builder` was based on), are there any concerns about adding `CAP_NET_RAW` to the binary by default?
=> feat: Build with CAP_NET_RAW by default to simplify rootless use

.goreleaser.yml, dist/ping_exporter.d/systemd-233.conf, dist/ping_exporter.d/systemd-235.conf, dist/ping_exporter.d/systemd-242.conf, dist/ping_exporter.d/systemd-245.conf, dist/ping_exporter.service, dist/ping_exporter.yaml, dist/postinstall.sh, dist/postremove.sh, dist/preremove.sh
I'd like to get the ping exporter running on Ubiquiti EdgeRouter Lite devices. The platform is MIPS (MIPS64 actually), and the EdgeOS running the device is a Debian 9 derivative.
This PR adds support for that platform (for good measure, I've also added a bunch more platforms I've seen and used on network equipment).
One notable change happened to the Debian packages build by goreleaser, as they are now fully self-contained. Installing the package will:
- create an unprivileged system user (aptly named `ping_exporter`),
- copy a config file to `/etc/ping_exporter/config.yml` (a slimmed down version of the example found in the README),
- install a systemd unit, and
- start the unit.
To get the systemd unit hardening applied to both the ancient version on EdgeOS (systemd 232) as well as …
=> Add support for various architectures and systemd versions

.github/workflows/lint.yml, .github/workflows/test.yml, .gitignore, README.md, config/config.go, config/config_test.go, config/testdata/config_test.yml, main.go, target.go, target_test.go
I don't have IPv6 support where I am using this, so I wanted to stop the metrics coming in for all the failed IPv6 addresses.
This is a bit of a superfluous feature and, of course, the failed IPv6 metrics can just be filtered out by using the label `ip_version="4"`, but it just bothered me having useless metrics scraped in and hanging around. 
I made a new section in the config which is very generically called `options`, mostly because I couldn't think of a different heading to put this single setting under. I figure `options` could be for any future miscellaneous, uncategorized settings? 🤷
=> Feature: disable ipv6 addresses

README.md
From latest, the parameter is `ping.size`. With this, I get `ping_rtt_best_seconds`, `ping_rtt_mean_seconds` etc. metrics, with the existing example using `ping.payload-size` all I get is `ping_loss_ratio`.
```
docker exec -it ping_exporter /bin/sh
/app # ./ping_exporter --help
usage: ping_exporter [<flags>] [<targets>...]
Flags:
--help                        Show context-sensitive help (also try --help-long and --help-man).
--version                     Print version information
--web.listen-address=":9427"  Address on which to expose metrics and web interface
--web.telemetry-path="/metrics"  
Path under which to expose metrics
--config.path=""              Path to config file
--ping.interval=5s            Interval for ICMP echo requests
--ping.timeout=4s             Timeout for ICMP …
```
=> Fix example usage of ping.size

dist/charts/ping-exporter/templates/deployment.yaml, dist/charts/ping-exporter/values.yaml
Add:
- Support to define rollout strategy (default to RollingUpdate).
- Support to define custom podLabels (could be useful for observability purposes)
=> helm: add strategy and podLabels

main.go
Added TLS (1.2 and newer) support for web server.
Added `--web.tls` kingping flags for TLS-handling. Also added client's certificate verification support (`--web.tls.mutual-auth-enabled` flag).
=> Web server HTTPS support

README.md, go.mod, go.sum, main.go, tailscale.go, target.go
The list of targets will be changed without restarting the exporter. This will not erase the history data of other ping targets, but enables the user to have a dynamic set of targets.
=> Implement hot reloading of configuration file for changed list of targets

config/config.go, config/config_test.go, config/duration.go, config/target.go, target.go
This changes allows other go code bases to serialize the configuration to a file.
=> Make configuration serializable

collector.go, main.go, rttscale.go, target.go
Improve speedup time by doing the intial DNS resolution also in parallel.
Fix edge cases if big files are created and truncated.
Refactor the ping collector such that it doesn't rely on global variables anymore. Add support for updating the target configs such that the label values can be updated per target. The set of labels names is not updated, as this will break the prometheus Collector interface.
=> Fix bugs introduced by hot reloading of targets

README.md
The source code checks for `payload-size`, not `size`.
=> Fix "size" to "payload-size" in README.md

dist/charts/ping-exporter/files/prometheus.rules, dist/charts/ping-exporter/templates/prometheusrule.yaml, dist/charts/ping-exporter/templates/servicemonitor.yaml, dist/charts/ping-exporter/values.yaml
Hi there, I started using this project recently so I decided to contribute support for the Prometheus Operator. This change only affects the Helm chart, but allows seamless integration for people using Kubernetes and the Prometheus Operator.
Setting `serviceMonitor.enabled: true` creates a serviceMonitor resource which makes Prometheus start scraping the exporter.
Setting `prometheusRules.enabled: true` adds some basic Prometheus alerting rules which alert on high latency or high packet loss.
This is tested & working on my Prometheus Operator stack.
Do you need me to bump the chart version before you merge?
=> Prometheus Operator support

config/config.go, config/config_test.go, config/testdata/config_test.yml, main.go, target.go
closes #134 
when running with `--dns.timeout=3s` you get the following output:
```
time="2025-03-31T21:07:12Z" level=info msg="rtt units: 2" func=main.main file="/go/ping_exporter/main.go:94"
time="2025-03-31T21:07:12Z" level=info msg="DNS timeout enabled: using 3000000000" func="main.(*target).addOrUpdateMonitor" file="/go/ping_exporter/target.go:93"
time="2025-03-31T21:07:12Z" level=info msg="DNS timeout enabled: using 3000000000" func="main.(*target).addOrUpdateMonitor" file="/go/ping_exporter/target.go:93"
time="2025-03-31T21:07:12Z" level=info msg="DNS timeout enabled: using 3000000000" func="main.(*target).addOrUpdateMonitor" file="/go/ping_exporter/target.go:93"
time="2025-03-31T21:07:12Z" level=info msg="adding target for host 2001:4860:4860::8844 ({2001:4860:4860::8844 })" …
```
=> feat(ping_exporter): add dns resolution timeout option
